### ISSUE TITLE
NotificationService (Synology Indexer)

### ISSUE THREAD

**Issue by arette** [VoliKoN/lidarr-docker#4]
I'm using a package that allows my docker containers to reach the synology indexer in /usr/syno/bin/synoindex (https://github.com/racklin/simple-synoindex-server).  This package works great with Sonarr/Radarr/etc. and I'm mapping the volume the same way in the container in Lidarr (/docker/simple-synoindex-server -> /usr/syno/bin), but alas the synology indexer does not appear to be called in the trace debug log I turned on to monitor a download event.  I do see NotificationService get invoked for each TrackImportedEvent, and I did receive Gmail notification for each track but synology database was not updated with new tracks and 'synoindex' did not appear to be called at all in the trace debug logs.  Note also that it passes the test in the Settings -> Connect -> Synoindex.  Is this feature possibly still incomplete?  Thanks!

**Comment by VoliKoN** [comment]
Looks like a Lidarr problem, you should open an issue on https://github.com/lidarr/Lidarr.
Thanks!
