### ISSUE TITLE
json.log size

### ISSUE THREAD

**Issue by woble** [VoliKoN/lidarr-docker#5]
For some reason the `*.json.log` file grows uncontrollably and fast as well. At some point it was 8GB. Running this on unraid would max out the size of the docker.img.

**Comment by VoliKoN** [comment]
On my machine its 155M after running for 4 weeks.
There's probably something wrong in your container that outputting errors, please check it.

Anyway if you want to limit the logs read this:
[https://stackoverflow.com/questions/31829587/docker-container-logs-taking-all-my-disk-space](https://stackoverflow.com/questions/31829587/docker-container-logs-taking-all-my-disk-space)

**Comment by woble** [comment]
Restarted the docker and in no time it jumps to about 40MB. Seems like Lidarr is checking through all of the nzbget history for some reason, including tv and movies. Gonna have to do some more investigation, but I doubt it's related to the docker. What you proposed can't be done nice and easy on unRAID unfortunately. They do have a feature coming where you could clamp logging across all dockers though.

**Comment by Qstick** [comment]
This should be fixed lidarr/Lidarr@aab78a62e68b28fd7115ae69edf5b704456f6389

**Comment by VoliKoN** [comment]
Thanks @Qstick !
