### ISSUE TITLE
Backend reload every 3 minutes or so

### ISSUE THREAD

**Issue by slimshizn** [VoliKoN/lidarr-docker#7]
I keep having an issue with the backend wanting to be reloaded, not sure why because out of sonarr,radarr,nzbget, and literally any other app on the same device has zero reloading issues or connection issues. How can I fix this?

**Comment by slimshizn** [comment]
![image](https://user-images.githubusercontent.com/23506499/36710803-2a7800b4-1b4e-11e8-8334-21656884f98e.png)

**Comment by VoliKoN** [comment]
You should contact Lidarr's devs at [https://github.com/lidarr/Lidarr](https://github.com/lidarr/Lidarr)
